-- =============================================================================
-- KCA INDIAN TALENT SCAN (ITS) -- POSTGRESQL SCHEMA
-- Kerala Catholic Association, Bahrain  |  talentscan.kcabah.com
-- =============================================================================
-- Target: PostgreSQL 14+ (uses GENERATED ALWAYS AS ... STORED columns)
-- Run on a fresh database/schema. To rebuild from scratch:
--   DROP SCHEMA public CASCADE; CREATE SCHEMA public;
--
-- DESIGN-RULE TRACEABILITY
-- Every constraint/trigger below is commented with the rule number(s) from the
-- Master Context it enforces, e.g. "rule #3". Rule list for reference:
--   1  All annual parameters live in year_config -- nothing hard-coded per year
--   2  PDFs include KCA logo + sponsor logo from year_config
--   3  Chest numbers assigned randomly on the day, post-attendance; time-slot
--      mode = lot draw per slot, continuous numbering across slots
--   4  Manual chest number entry restricted to Chairman/SuperAdmin
--   5  Judges see chest numbers only, never participant names
--   6  Live ranking visible only to the scoring judge as they enter scores
--   7  Divergence threshold = % of total participants (year_config-driven)
--   8  Exact tie -> Chairman-unlocked tiebreaker marks (1-10/judge), logged
--   9  Judge refusal -> mandatory statement -> judge_flags -> Chairman notified
--   10 Judge blacklist warns admin on assignment, tracked annually
--   11 Judge contact info restricted to SuperAdmin + Chairman
--   12 OTP sent manually by Convener/Admin at briefing, not automatically
--   13 Two-stage result publication: Finalise+Print -> Chairman publish to PWA
--   14 Extra/consolation 4th-place prize: Chairman only, before Stage 2, no rank pts
--   15 Group Championship = one award per age group, gender-agnostic
--   16 School awards = SUM(rank_points + grade_points + participation_bonus_pts)
--   17 Teacher name 'NOT_APPLICABLE' option, excluded from teacher awards
--   18 Teacher name deadline configurable, can be updated post-contest
--   19 Team attendance confirmed per member; substitutions need Admin approval
--   20 Cancelled event -> one swap window after initial list publication
--   21 PWA login = first 4 chars of name + last 4 digits of CPR
--   22 Chest numbers never shown in PWA
--   23 PWA "My Results" = per-event grade/rank pts/grade pts + running totals
--   24 Awards screen restricted to Chairman role
--   25 audit_log is INSERT-ONLY
--   26 Auto Schedule Draft generated by scheduler.js from Admin inputs
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS citext;

-- =============================================================================
-- SECTION 0: ENUM TYPES
-- =============================================================================

CREATE TYPE user_role AS ENUM ('SuperAdmin','Admin','Coordinator','Chairman','Judge','Viewer');
CREATE TYPE event_kind AS ENUM ('individual','team');
CREATE TYPE registration_status AS ENUM ('registered','attended','absent','withdrawn','swapped');

-- =============================================================================
-- SECTION 1: SETUP / YEAR CONFIGURATION
-- =============================================================================

CREATE TABLE year_config (
    id                          SERIAL PRIMARY KEY,
    year                        INT NOT NULL UNIQUE,                 -- calendar year, e.g. 2026
    event_year_label            TEXT NOT NULL,                       -- e.g. 'KCA Indian Talent Scan 2026'
    is_active                   BOOL NOT NULL DEFAULT FALSE,         -- the single "current" year app operates on
    kca_logo_url                TEXT,
    sponsor_logo_url            TEXT,
    sponsor_name                TEXT,
    kca_iban                    TEXT,
    benefit_pay_number          TEXT,
    max_individual_events       INT NOT NULL DEFAULT 12,
    category_cap                INT NOT NULL DEFAULT 6,
    kca_special_min_points      INT NOT NULL DEFAULT 30,
    min_entries_threshold       INT NOT NULL DEFAULT 5,
    split_threshold             INT NOT NULL DEFAULT 25,
    no_prize_below              INT NOT NULL DEFAULT 3,
    rank_pts_first              NUMERIC(6,2) NOT NULL DEFAULT 5,
    rank_pts_second             NUMERIC(6,2) NOT NULL DEFAULT 3,
    rank_pts_third              NUMERIC(6,2) NOT NULL DEFAULT 1,
    participation_bonus_pts     NUMERIC(6,2) NOT NULL DEFAULT 0.5,
    grade_a_pct                 NUMERIC(5,2) NOT NULL DEFAULT 70,
    grade_b_pct                 NUMERIC(5,2) NOT NULL DEFAULT 50,
    grade_a_pts                 NUMERIC(6,2) NOT NULL DEFAULT 3,
    grade_b_pts                 NUMERIC(6,2) NOT NULL DEFAULT 2,
    grade_c_pts                 NUMERIC(6,2) NOT NULL DEFAULT 1,
    divergence_threshold_pct    NUMERIC(5,2) NOT NULL DEFAULT 20,    -- rule #7
    reg_deadline                TIMESTAMPTZ,
    team_reg_deadline           TIMESTAMPTZ,
    teacher_name_deadline       TIMESTAMPTZ,                        -- rule #18
    result_template_url         TEXT,
    photo_crop_width            INT NOT NULL DEFAULT 413,
    photo_crop_height           INT NOT NULL DEFAULT 531,
    initial_list_published      BOOL NOT NULL DEFAULT FALSE,         -- gates the rule #20 swap window
    initial_list_published_at   TIMESTAMPTZ,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (grade_a_pct BETWEEN 0 AND 100),
    CHECK (grade_b_pct BETWEEN 0 AND 100),
    CHECK (grade_a_pct > grade_b_pct),
    CHECK (divergence_threshold_pct BETWEEN 0 AND 100)
);
COMMENT ON TABLE year_config IS 'One row per competition year. ALL annual/tunable parameters live here (rule #1) -- nothing year-specific should ever be hard-coded in application code. Every other table that varies by year hangs off year_id.';
COMMENT ON COLUMN year_config.kca_logo_url IS 'Used on every generated PDF together with sponsor_logo_url (rule #2).';
COMMENT ON COLUMN year_config.divergence_threshold_pct IS 'Absolute divergence threshold per event = ROUND(total_participants * pct / 100) -- see fn_divergence_abs_threshold() (rule #7).';

-- Only one year may be "active" at a time.
CREATE UNIQUE INDEX ux_year_config_single_active ON year_config (is_active) WHERE is_active = TRUE;

CREATE TABLE users (
    id              SERIAL PRIMARY KEY,
    full_name       TEXT NOT NULL,
    email           CITEXT UNIQUE,
    phone           TEXT,
    password_hash   TEXT NOT NULL,
    role            user_role NOT NULL,
    is_active       BOOL NOT NULL DEFAULT TRUE,
    last_login_at   TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE users IS 'JWT-authenticated application users. role drives both API authorization and several DB-level checks below (the app must SET LOCAL app.current_role / app.current_user_id per request -- see SECTION 9).';

CREATE TABLE schools (
    id              SERIAL PRIMARY KEY,
    name            TEXT NOT NULL,
    short_code      TEXT UNIQUE,
    contact_person  TEXT,
    contact_phone   TEXT,
    contact_email   TEXT,
    address         TEXT,
    is_active       BOOL NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE schools IS 'Participating units/schools/parish groups -- the award unit for School Awards (rule #16) and Group Championship (rule #15).';

CREATE TABLE age_groups (
    id          SERIAL PRIMARY KEY,
    year_id     INT NOT NULL REFERENCES year_config(id) ON DELETE CASCADE,
    code        TEXT NOT NULL,           -- 'G1'..'G5'
    label       TEXT NOT NULL,           -- e.g. 'Sub Junior (5-7 yrs)'
    dob_from    DATE NOT NULL,
    dob_to      DATE NOT NULL,
    sort_order  INT NOT NULL DEFAULT 0,
    UNIQUE (year_id, code),
    CHECK (dob_from <= dob_to)
);
COMMENT ON TABLE age_groups IS 'DOB-based age groups, redefined every year (rule #1). A participant''s age_group_id is auto-derived from DOB via fn_assign_age_group().';

CREATE TABLE categories (
    id          SERIAL PRIMARY KEY,
    year_id     INT NOT NULL REFERENCES year_config(id) ON DELETE CASCADE,
    code        TEXT NOT NULL,
    name        TEXT NOT NULL,
    sort_order  INT NOT NULL DEFAULT 0,
    UNIQUE (year_id, code)
);
COMMENT ON TABLE categories IS 'The ~6 event categories, configured per year so they can be renamed/added/retired without code changes (rule #1).';

CREATE TABLE events (
    id                          SERIAL PRIMARY KEY,
    year_id                     INT NOT NULL REFERENCES year_config(id) ON DELETE CASCADE,
    category_id                 INT REFERENCES categories(id),
    event_code                  TEXT NOT NULL,
    event_name                  TEXT NOT NULL,
    event_kind                  event_kind NOT NULL DEFAULT 'individual',
    is_stage_event              BOOL NOT NULL DEFAULT TRUE,
    max_participants_per_team   INT,
    min_participants_per_team   INT,
    time_slot_mode              BOOL NOT NULL DEFAULT FALSE,    -- rule #3
    is_cancelled                BOOL NOT NULL DEFAULT FALSE,    -- rule #20
    cancelled_at                TIMESTAMPTZ,
    cancel_reason               TEXT,
    cancelled_by                INT REFERENCES users(id),
    sort_order                  INT NOT NULL DEFAULT 0,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (year_id, event_code)
);
COMMENT ON TABLE events IS '~54 individual + 9 team events per year. time_slot_mode flags high-volume events that use lot-draw-per-slot with continuous chest numbering (rule #3). is_cancelled drives the rule #20 one-time swap window.';

CREATE INDEX idx_events_year ON events(year_id);

CREATE TABLE event_age_groups (
    event_id      INT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    age_group_id  INT NOT NULL REFERENCES age_groups(id) ON DELETE CASCADE,
    PRIMARY KEY (event_id, age_group_id)
);
COMMENT ON TABLE event_age_groups IS 'Which age groups a given event is open to.';

CREATE TABLE event_criteria (
    id               SERIAL PRIMARY KEY,
    event_id         INT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    criterion_name   TEXT NOT NULL,
    max_score        NUMERIC(5,2) NOT NULL CHECK (max_score > 0),
    sequence_order   INT NOT NULL DEFAULT 1,
    UNIQUE (event_id, sequence_order)
);
COMMENT ON TABLE event_criteria IS 'Up to 6 scoring criteria per event; the max_score values must sum to 100 -- enforced by trg_event_criteria_check.';

CREATE TABLE event_time_slots (
    id                      SERIAL PRIMARY KEY,
    event_id                INT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    sub_group               CHAR(1),                 -- batch label within the event, e.g. 'A','B','C'
    slot_label              TEXT NOT NULL,
    reporting_time          TIME,
    participant_capacity    INT NOT NULL CHECK (participant_capacity > 0),
    chest_no_start           INT,                     -- auto-computed, see fn_recalc_slot_chest_numbers()
    sort_order               INT NOT NULL DEFAULT 1,
    UNIQUE (event_id, slot_label)
);
COMMENT ON TABLE event_time_slots IS 'For time_slot_mode events: one row per lot-draw slot. chest_no_start is recalculated automatically so chest numbers stay continuous across all slots of the event (rule #3).';

-- =============================================================================
-- SECTION 2: JUDGES
-- =============================================================================

CREATE TABLE judges (
    id                SERIAL PRIMARY KEY,
    user_id           INT REFERENCES users(id),       -- optional login account
    full_name         TEXT NOT NULL,
    phone             TEXT,
    whatsapp          TEXT,
    email             TEXT,
    bio               TEXT,
    is_blacklisted    BOOL NOT NULL DEFAULT FALSE,     -- rule #10
    blacklist_reason  TEXT,
    blacklist_date    DATE,
    blacklisted_by    INT REFERENCES users(id),
    otp_code          TEXT,                            -- rule #12
    otp_sent_at       TIMESTAMPTZ,
    otp_sent_by       INT REFERENCES users(id),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE judges IS 'phone/whatsapp/email are restricted fields -- the API must only expose them to SuperAdmin/Chairman (rule #11). Use the v_judges_public view for every other role. otp_code is set manually by Convener/Admin at briefing time, never automatically (rule #12).';
COMMENT ON COLUMN judges.is_blacklisted IS 'trg_judge_assignment_blacklist_warning raises a WARNING when a blacklisted judge is assigned (rule #10); the app should surface this to the assigning Admin and it feeds the annual blacklist report.';

CREATE INDEX idx_judges_is_blacklisted ON judges(is_blacklisted);

CREATE TABLE judge_flags (
    id                       SERIAL PRIMARY KEY,
    judge_id                 INT NOT NULL REFERENCES judges(id),
    event_id                 INT REFERENCES events(id),
    year_id                  INT NOT NULL REFERENCES year_config(id),
    flag_type                TEXT NOT NULL CHECK (flag_type IN ('declined_revision','bias_noted')),
    statement                TEXT NOT NULL,
    flagged_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    reviewed_by_chairman     BOOL NOT NULL DEFAULT FALSE
);
COMMENT ON TABLE judge_flags IS 'Created when a judge refuses a divergence/tie review (rule #9). statement is mandatory; Chairman is notified and reviews via reviewed_by_chairman.';

CREATE INDEX idx_judge_flags_judge_year ON judge_flags(judge_id, year_id);

CREATE TABLE judge_assignments (
    id              SERIAL PRIMARY KEY,
    judge_id        INT NOT NULL REFERENCES judges(id),
    event_id        INT NOT NULL REFERENCES events(id),
    time_slot_id    INT REFERENCES event_time_slots(id),
    assigned_by     INT REFERENCES users(id),
    assigned_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (judge_id, event_id, time_slot_id)
);
COMMENT ON TABLE judge_assignments IS 'Exactly 3 judges expected per event (enforced at application level / report, not a hard DB constraint to allow temporary under/over-assignment while staffing).';

-- =============================================================================
-- SECTION 3: PARTICIPANTS & MEMBERSHIP
-- =============================================================================

CREATE TABLE participants (
    id                  SERIAL PRIMARY KEY,
    year_id             INT NOT NULL REFERENCES year_config(id),
    school_id           INT REFERENCES schools(id),
    cpr_number          TEXT NOT NULL,
    full_name           TEXT NOT NULL,
    dob                 DATE NOT NULL,
    gender              CHAR(1) CHECK (gender IN ('M','F')),
    age_group_id        INT REFERENCES age_groups(id),       -- auto-derived, see fn_assign_age_group()
    guardian_name       TEXT,
    guardian_phone      TEXT,
    photo_url           TEXT,
    cpr_scan_url        TEXT,
    membership_status   TEXT,
    pwa_username        TEXT,                                -- auto-derived, see fn_generate_pwa_username()
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (year_id, cpr_number)
);
COMMENT ON TABLE participants IS 'One row per participant per year. age_group_id and pwa_username are computed automatically by triggers -- never set them directly from the app.';
COMMENT ON COLUMN participants.pwa_username IS 'PWA login identifier = first 4 chars of full_name + last 4 digits of cpr_number (rule #21), lower-cased. Chest numbers are NEVER exposed via the PWA (rule #22) -- this column has nothing to do with chest numbers.';

CREATE INDEX idx_participants_year_cpr ON participants(year_id, cpr_number);

CREATE TABLE membership_verifications (
    id               SERIAL PRIMARY KEY,
    participant_id   INT REFERENCES participants(id),
    cpr_number       TEXT NOT NULL,
    member_status    TEXT,
    family_id        TEXT,
    raw_response     JSONB,
    checked_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    checked_by       INT REFERENCES users(id)
);
COMMENT ON TABLE membership_verifications IS 'Cache/audit trail of lookups against the live KCA membership API (mem.kcabah.com).';

-- =============================================================================
-- SECTION 4: TEAMS & TEAM MEMBERS
-- =============================================================================

CREATE TABLE teams (
    id            SERIAL PRIMARY KEY,
    year_id       INT NOT NULL REFERENCES year_config(id),
    event_id      INT NOT NULL REFERENCES events(id),
    school_id     INT REFERENCES schools(id),
    age_group_id  INT REFERENCES age_groups(id),
    team_name     TEXT NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (event_id, team_name)
);
COMMENT ON TABLE teams IS 'One row per team entered into one of the 9 team events.';

CREATE TABLE team_members (
    id                       SERIAL PRIMARY KEY,
    team_id                  INT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    participant_id           INT NOT NULL REFERENCES participants(id),
    is_substitute            BOOL NOT NULL DEFAULT FALSE,
    substitute_reason        TEXT,
    approved_by              INT REFERENCES users(id),
    approved_at              TIMESTAMPTZ,
    attendance_confirmed     BOOL NOT NULL DEFAULT FALSE,    -- rule #19: each member confirmed individually
    confirmed_by             INT REFERENCES users(id),
    confirmed_at             TIMESTAMPTZ,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (team_id, participant_id),
    CHECK (NOT is_substitute OR approved_by IS NOT NULL)      -- rule #19: substitutions require Admin approval
);
COMMENT ON TABLE team_members IS 'Per rule #19: every member''s attendance is confirmed individually (attendance_confirmed/confirmed_by/confirmed_at) and any substitution requires an approving Admin (approved_by) -- the CHECK constraint makes this non-negotiable at the DB level. All changes are additionally captured in audit_log.';

CREATE INDEX idx_team_members_team ON team_members(team_id);

-- =============================================================================
-- SECTION 5: REGISTRATIONS
-- =============================================================================

CREATE TABLE registrations (
    id                       SERIAL PRIMARY KEY,
    year_id                  INT NOT NULL REFERENCES year_config(id),
    participant_id           INT REFERENCES participants(id),
    team_id                  INT REFERENCES teams(id),
    event_id                 INT NOT NULL REFERENCES events(id),
    age_group_id             INT NOT NULL REFERENCES age_groups(id),
    category_id              INT REFERENCES categories(id),
    time_slot_id             INT REFERENCES event_time_slots(id),
    status                   registration_status NOT NULL DEFAULT 'registered',
    dance_teacher             TEXT,   -- NULL, 'NOT_APPLICABLE', or teacher name (rule #17)
    music_teacher              TEXT,   -- NULL, 'NOT_APPLICABLE', or teacher name (rule #17)
    attendance_marked_by      INT REFERENCES users(id),
    attendance_marked_at      TIMESTAMPTZ,
    registered_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    registered_by             INT REFERENCES users(id),
    updated_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK ((participant_id IS NOT NULL AND team_id IS NULL) OR (participant_id IS NULL AND team_id IS NOT NULL))
);
COMMENT ON TABLE registrations IS 'One row per individual-event entry (participant_id set) or per team-event entry (team_id set). dance_teacher/music_teacher accept the literal value ''NOT_APPLICABLE'' for self-taught participants, who are then excluded from teacher awards by application logic (rule #17); the editable window is governed by year_config.teacher_name_deadline (rule #18), which the app may relax even after contests conclude.';

CREATE UNIQUE INDEX ux_registrations_participant_event ON registrations(participant_id, event_id) WHERE participant_id IS NOT NULL;
CREATE UNIQUE INDEX ux_registrations_team_event ON registrations(team_id, event_id) WHERE team_id IS NOT NULL;
CREATE INDEX idx_registrations_event_participant ON registrations(event_id, participant_id);

CREATE TABLE event_swap_requests (
    id                  SERIAL PRIMARY KEY,
    registration_id     INT NOT NULL UNIQUE REFERENCES registrations(id),  -- UNIQUE => exactly one swap window (rule #20)
    original_event_id   INT NOT NULL REFERENCES events(id),
    new_event_id        INT REFERENCES events(id),
    reason               TEXT,
    status                TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected')),
    requested_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    requested_by          INT REFERENCES users(id),
    approved_by           INT REFERENCES users(id),
    approved_at           TIMESTAMPTZ
);
COMMENT ON TABLE event_swap_requests IS 'Rule #20: if an event is cancelled after the initial list is published, affected participants get exactly ONE swap. The UNIQUE constraint on registration_id enforces "one window" at the database level.';

-- =============================================================================
-- SECTION 6: CHEST NUMBERS
-- =============================================================================

CREATE TABLE chest_assignments (
    id                SERIAL PRIMARY KEY,
    year_id           INT NOT NULL REFERENCES year_config(id),
    event_id          INT NOT NULL REFERENCES events(id),
    time_slot_id      INT REFERENCES event_time_slots(id),
    registration_id   INT NOT NULL UNIQUE REFERENCES registrations(id),
    chest_number      INT NOT NULL CHECK (chest_number > 0),
    allocation_mode   TEXT NOT NULL CHECK (allocation_mode IN ('auto','timeslot','manual')),
    allocated_by      INT NOT NULL REFERENCES users(id),
    allocated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (event_id, chest_number)
);
COMMENT ON TABLE chest_assignments IS 'Chest numbers are assigned the day of the event, after attendance is marked -- never in advance (rule #3). allocation_mode = manual is restricted to Chairman/SuperAdmin and enforced by trg_chest_manual_role_check (rule #4).';

-- =============================================================================
-- SECTION 7: SCORING, TIES & RESULTS
-- =============================================================================

CREATE TABLE scores (
    id                     BIGSERIAL PRIMARY KEY,
    judge_assignment_id    INT NOT NULL REFERENCES judge_assignments(id),
    registration_id        INT NOT NULL REFERENCES registrations(id),
    criterion_id           INT NOT NULL REFERENCES event_criteria(id),
    score_value            NUMERIC(5,2) NOT NULL CHECK (score_value >= 0),
    entered_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    entered_by             INT REFERENCES users(id),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (judge_assignment_id, registration_id, criterion_id)
);
COMMENT ON TABLE scores IS 'One row per judge x participant x criterion. trg_scores_check_max guarantees score_value never exceeds the criterion''s max_score. The "live ranking visible only to the scoring judge" rule (#6) and "judges see chest numbers only" rule (#5) are enforced at the API layer via v_judge_scoring_board -- judges'' read access should never touch participants or registrations directly.';

CREATE TABLE tiebreaker_unlocks (
    id            SERIAL PRIMARY KEY,
    event_id      INT NOT NULL REFERENCES events(id),
    sub_group     CHAR(1),
    unlocked_by   INT NOT NULL REFERENCES users(id),
    unlocked_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    locked_at     TIMESTAMPTZ
);
COMMENT ON TABLE tiebreaker_unlocks IS 'A Chairman must explicitly unlock a tiebreaker session for an event/sub_group before an Admin can key in marks (rule #8). trg_tiebreaker_marks_check_unlock verifies unlocked_by holds the Chairman role and that the session is not yet locked.';

CREATE TABLE tiebreaker_marks (
    id                        SERIAL PRIMARY KEY,
    event_id                  INT NOT NULL REFERENCES events(id),
    sub_group                 CHAR(1),
    participant_reg_id        INT NOT NULL REFERENCES registrations(id),
    judge_id                  INT NOT NULL REFERENCES judges(id),
    mark                      INT NOT NULL CHECK (mark BETWEEN 1 AND 10),
    unlock_id                 INT NOT NULL REFERENCES tiebreaker_unlocks(id),
    entered_by                INT NOT NULL REFERENCES users(id),
    approved_by_chairman      INT REFERENCES users(id),
    entered_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (participant_reg_id, judge_id, unlock_id)
);
COMMENT ON TABLE tiebreaker_marks IS 'Exact-tie process (rule #8): each judge gives a 1-10 mark per tied participant; Admin keys it in under Chairman supervision; everything is captured in audit_log via trg_audit_tiebreaker_marks.';

CREATE TABLE event_results (
    id                          SERIAL PRIMARY KEY,
    registration_id             INT NOT NULL UNIQUE REFERENCES registrations(id),
    event_id                    INT NOT NULL REFERENCES events(id),
    prize_place                 INT CHECK (prize_place > 0),
    grade                       CHAR(1) CHECK (grade IN ('A','B','C')),
    extra_prize_type            TEXT CHECK (extra_prize_type IS NULL OR extra_prize_type IN ('additional_3rd','consolation')),
    extra_prize_approved_by     INT REFERENCES users(id),
    rank_points                 NUMERIC(6,2) NOT NULL DEFAULT 0,   -- 0 for any extra/consolation prize (rule #14)
    grade_points                NUMERIC(6,2) NOT NULL DEFAULT 0,
    participation_bonus_pts     NUMERIC(6,2) NOT NULL DEFAULT 0,
    total_points                NUMERIC(6,2) GENERATED ALWAYS AS (rank_points + grade_points + participation_bonus_pts) STORED,
    tie_flag                    BOOL NOT NULL DEFAULT FALSE,
    divergence_flag              BOOL NOT NULL DEFAULT FALSE,
    divergence_notes             TEXT,
    is_finalised                 BOOL NOT NULL DEFAULT FALSE,        -- Stage 1 (rule #13)
    finalised_by                  INT REFERENCES users(id),
    finalised_at                  TIMESTAMPTZ,
    is_published                  BOOL NOT NULL DEFAULT FALSE,        -- Stage 2 (rule #13)
    published_by                  INT REFERENCES users(id),
    published_at                  TIMESTAMPTZ,
    created_at                    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (NOT is_published OR is_finalised),                          -- can't publish before finalising (rule #13)
    CHECK (extra_prize_type IS NULL OR extra_prize_approved_by IS NOT NULL)
);
COMMENT ON TABLE event_results IS 'total_points (= rank_points + grade_points + participation_bonus_pts) is a generated column, guaranteeing the school-award formula (rule #16) is always consistent. The CHECK on is_published/is_finalised enforces the two-stage publication workflow (rule #13): Finalise+Print for signatures, then Chairman publishes to the PWA.';
COMMENT ON COLUMN event_results.extra_prize_type IS 'Chairman-only "4th place" extra/consolation prize, addable only before Stage 2 publication (rule #14) -- enforced by trg_event_results_extra_prize_window. Carries no rank_points.';

CREATE INDEX idx_event_results_registration ON event_results(registration_id);

-- =============================================================================
-- SECTION 8: SCHEDULING & NOTIFICATIONS
-- =============================================================================

CREATE TABLE schedule (
    id                          SERIAL PRIMARY KEY,
    year_id                      INT NOT NULL REFERENCES year_config(id),
    event_id                     INT NOT NULL REFERENCES events(id),
    time_slot_id                 INT REFERENCES event_time_slots(id),
    judge_assignment_id          INT REFERENCES judge_assignments(id),
    event_date                   DATE NOT NULL,
    start_time                   TIME,
    end_time                     TIME,
    venue                        TEXT,
    status                       TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','confirmed','completed')),
    generated_by_scheduler       BOOL NOT NULL DEFAULT TRUE,
    created_at                   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                   TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE schedule IS 'Populated by scheduler.js as a conflict-free, judge-efficient draft from Admin inputs (rule #26); status moves draft -> confirmed -> completed.';

CREATE INDEX idx_schedule_year_date ON schedule(year_id, event_date);

CREATE TABLE notifications_log (
    id                       BIGSERIAL PRIMARY KEY,
    recipient_type           TEXT CHECK (recipient_type IN ('judge','participant','guardian','school','admin')),
    recipient_id             INT,
    channel                  TEXT NOT NULL CHECK (channel IN ('whatsapp','sms','email')),
    purpose                  TEXT,         -- e.g. 'otp','result_alert','reminder'
    message                  TEXT,
    status                   TEXT NOT NULL DEFAULT 'queued' CHECK (status IN ('queued','sent','failed','delivered')),
    provider                 TEXT,         -- 'green_api' | 'whatsapp_business_api' | ...
    provider_response        JSONB,
    sent_by                  INT REFERENCES users(id),
    sent_at                  TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE notifications_log IS 'Pluggable WhatsApp/SMS/Email send log (Green API or WhatsApp Business API). purpose=''otp'' rows correspond to the manual OTP send described in rule #12.';

-- =============================================================================
-- SECTION 9: AUDIT LOG (INSERT-ONLY)
-- =============================================================================

CREATE TABLE audit_log (
    id            BIGSERIAL PRIMARY KEY,
    table_name    TEXT NOT NULL,
    record_id     BIGINT,
    action        TEXT NOT NULL CHECK (action IN ('INSERT','UPDATE','DELETE')),
    old_value     JSONB,
    new_value     JSONB,
    changed_by    INT REFERENCES users(id),
    reason        TEXT,
    changed_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE audit_log IS 'Append-only ledger (rule #25). Populated by fn_audit_log() triggers on sensitive tables. Application connects as role kca_app, which has UPDATE/DELETE explicitly revoked below -- there is no code path, buggy or malicious, that can alter history short of a superuser/owner action outside the app.';

CREATE INDEX idx_audit_log_table_record ON audit_log(table_name, record_id);

-- =============================================================================
-- SECTION 10: VIEWS
-- =============================================================================

CREATE VIEW v_judges_public AS
SELECT id, full_name, bio, is_blacklisted, blacklist_reason, blacklist_date
FROM judges;
COMMENT ON VIEW v_judges_public IS 'Judge info safe for Admin/Coordinator/Viewer roles -- excludes phone/whatsapp/email per rule #11. SuperAdmin/Chairman query the judges table directly.';

CREATE VIEW v_judge_scoring_board AS
SELECT
    r.id            AS registration_id,
    r.event_id,
    r.time_slot_id,
    ca.chest_number
FROM registrations r
JOIN chest_assignments ca ON ca.registration_id = r.id
WHERE r.status = 'attended';
COMMENT ON VIEW v_judge_scoring_board IS 'The ONLY thing a judge''s scoring screen should query -- chest numbers only, never participant names (rule #5).';

CREATE VIEW v_school_award_totals AS
SELECT
    p.year_id,
    p.school_id,
    s.name AS school_name,
    SUM(er.rank_points)               AS total_rank_points,
    SUM(er.grade_points)              AS total_grade_points,
    SUM(er.participation_bonus_pts)   AS total_participation_pts,
    SUM(er.total_points)              AS grand_total
FROM event_results er
JOIN registrations r  ON r.id = er.registration_id
JOIN participants p   ON p.id = r.participant_id
JOIN schools s        ON s.id = p.school_id
WHERE er.is_finalised = TRUE
GROUP BY p.year_id, p.school_id, s.name;
COMMENT ON VIEW v_school_award_totals IS 'School award standings = SUM(rank_points + grade_points + participation_bonus_pts) per rule #16, individual-event results. Union with an equivalent team-event aggregate (via teams.school_id) for the full school total.';

CREATE VIEW v_group_championship AS
SELECT
    t.year_id,
    t.age_group_id,
    ag.label AS age_group_label,
    t.school_id,
    s.name   AS school_name,
    SUM(er.total_points) AS total_points
FROM event_results er
JOIN registrations r ON r.id = er.registration_id
JOIN teams t          ON t.id = r.team_id
JOIN age_groups ag    ON ag.id = t.age_group_id
JOIN schools s        ON s.id = t.school_id
WHERE er.is_finalised = TRUE
GROUP BY t.year_id, t.age_group_id, ag.label, t.school_id, s.name;
COMMENT ON VIEW v_group_championship IS 'Group Championship standings: ONE award per age group, gender-agnostic (rule #15) -- take the top school per age_group_id from this view.';

-- =============================================================================
-- SECTION 11: GENERIC TRIGGER FUNCTIONS
-- =============================================================================

CREATE OR REPLACE FUNCTION fn_set_updated_at() RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_audit_log() RETURNS TRIGGER AS $$
DECLARE
    v_user_id INT;
    v_reason  TEXT;
BEGIN
    -- The application must run: SELECT set_config('app.current_user_id', '<id>', true);
    -- and optionally: SELECT set_config('app.audit_reason', '<text>', true); at the start
    -- of each request/transaction.
    v_user_id := NULLIF(current_setting('app.current_user_id', true), '')::INT;
    v_reason  := current_setting('app.audit_reason', true);

    INSERT INTO audit_log(table_name, record_id, action, old_value, new_value, changed_by, reason)
    VALUES (
        TG_TABLE_NAME,
        COALESCE((NEW).id, (OLD).id),
        TG_OP,
        CASE WHEN TG_OP IN ('UPDATE','DELETE') THEN to_jsonb(OLD) ELSE NULL END,
        CASE WHEN TG_OP IN ('UPDATE','INSERT') THEN to_jsonb(NEW) ELSE NULL END,
        v_user_id,
        v_reason
    );
    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;
COMMENT ON FUNCTION fn_audit_log() IS 'Generic INSERT-ONLY audit trigger (rule #25). Reads app.current_user_id / app.audit_reason session settings set by the API layer per request.';

-- =============================================================================
-- SECTION 12: BUSINESS-RULE TRIGGER FUNCTIONS
-- =============================================================================

-- Rule #21: PWA login = first 4 chars of name + last 4 digits of CPR.
CREATE OR REPLACE FUNCTION fn_generate_pwa_username() RETURNS TRIGGER AS $$
BEGIN
    NEW.pwa_username := lower(left(NEW.full_name, 4) || right(NEW.cpr_number, 4));
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Auto-derive age_group_id from DOB against the year's configured age_groups.
CREATE OR REPLACE FUNCTION fn_assign_age_group() RETURNS TRIGGER AS $$
DECLARE
    v_age_group_id INT;
BEGIN
    SELECT id INTO v_age_group_id
    FROM age_groups
    WHERE year_id = NEW.year_id
      AND NEW.dob BETWEEN dob_from AND dob_to
    LIMIT 1;

    IF v_age_group_id IS NULL THEN
        RAISE EXCEPTION 'No age group configured for DOB % in year_id % (rule #1: configure age_groups for every year)', NEW.dob, NEW.year_id;
    END IF;

    NEW.age_group_id := v_age_group_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Rule: up to 6 criteria per event, max_score values sum to 100.
CREATE OR REPLACE FUNCTION fn_check_event_criteria() RETURNS TRIGGER AS $$
DECLARE
    v_event_id INT := COALESCE(NEW.event_id, OLD.event_id);
    v_count    INT;
    v_sum      NUMERIC;
BEGIN
    SELECT count(*), COALESCE(sum(max_score), 0) INTO v_count, v_sum
    FROM event_criteria WHERE event_id = v_event_id;

    IF v_count > 6 THEN
        RAISE EXCEPTION 'Event % cannot have more than 6 scoring criteria', v_event_id;
    END IF;

    IF v_sum > 100 THEN
        RAISE EXCEPTION 'Event % criteria max_score values sum to % -- must not exceed 100', v_event_id, v_sum;
    END IF;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- Score entries can never exceed their criterion's max_score.
CREATE OR REPLACE FUNCTION fn_check_score_max() RETURNS TRIGGER AS $$
DECLARE
    v_max NUMERIC;
BEGIN
    SELECT max_score INTO v_max FROM event_criteria WHERE id = NEW.criterion_id;
    IF NEW.score_value > v_max THEN
        RAISE EXCEPTION 'Score % exceeds criterion max_score % (criterion_id=%)', NEW.score_value, v_max, NEW.criterion_id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Rule #3: continuous chest numbering across all slots of a time-slot-mode event.
CREATE OR REPLACE FUNCTION fn_recalc_slot_chest_numbers() RETURNS TRIGGER AS $$
DECLARE
    v_event_id INT := COALESCE(NEW.event_id, OLD.event_id);
    v_running  INT := 1;
    r RECORD;
BEGIN
    FOR r IN
        SELECT id, participant_capacity
        FROM event_time_slots
        WHERE event_id = v_event_id
        ORDER BY sort_order, id
    LOOP
        UPDATE event_time_slots
        SET chest_no_start = v_running
        WHERE id = r.id AND chest_no_start IS DISTINCT FROM v_running;
        v_running := v_running + r.participant_capacity;
    END LOOP;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- Rule #4: manual chest number entry restricted to Chairman/SuperAdmin.
-- App must: SELECT set_config('app.current_role', '<JWT role>', true); per request.
CREATE OR REPLACE FUNCTION fn_enforce_manual_chest_role() RETURNS TRIGGER AS $$
DECLARE
    v_role TEXT := current_setting('app.current_role', true);
BEGIN
    IF NEW.allocation_mode = 'manual' THEN
        IF v_role IS NULL OR v_role NOT IN ('Chairman','SuperAdmin') THEN
            RAISE EXCEPTION 'Manual chest number entry is restricted to Chairman/SuperAdmin (rule #4). Current app role: %', COALESCE(v_role, 'unset');
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Rule #10: warn on assigning a blacklisted judge.
CREATE OR REPLACE FUNCTION fn_warn_blacklisted_judge() RETURNS TRIGGER AS $$
DECLARE
    v_blacklisted BOOL;
BEGIN
    SELECT is_blacklisted INTO v_blacklisted FROM judges WHERE id = NEW.judge_id;
    IF v_blacklisted THEN
        RAISE WARNING 'Judge % is BLACKLISTED -- assigning to event % requires admin acknowledgement (rule #10)', NEW.judge_id, NEW.event_id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Rule #8: tiebreaker marks require a Chairman-unlocked, still-open session.
CREATE OR REPLACE FUNCTION fn_check_tiebreaker_unlock() RETURNS TRIGGER AS $$
DECLARE
    v_locked_at TIMESTAMPTZ;
    v_role      user_role;
BEGIN
    SELECT tu.locked_at, u.role INTO v_locked_at, v_role
    FROM tiebreaker_unlocks tu
    JOIN users u ON u.id = tu.unlocked_by
    WHERE tu.id = NEW.unlock_id;

    IF v_role IS DISTINCT FROM 'Chairman' THEN
        RAISE EXCEPTION 'Tiebreaker session % was not unlocked by a Chairman (rule #8)', NEW.unlock_id;
    END IF;

    IF v_locked_at IS NOT NULL THEN
        RAISE EXCEPTION 'Tiebreaker session % is locked -- cannot enter further marks', NEW.unlock_id;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Rule #14: extra/consolation prize only addable before Stage 2 publication.
CREATE OR REPLACE FUNCTION fn_check_extra_prize_window() RETURNS TRIGGER AS $$
BEGIN
    IF NEW.extra_prize_type IS NOT NULL AND OLD.is_published = TRUE THEN
        RAISE EXCEPTION 'Extra/consolation prizes can only be added before Stage 2 (Chairman publish) -- rule #14';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Rule #1 integrity: category and event must belong to the same year_config.
CREATE OR REPLACE FUNCTION fn_check_event_category_year() RETURNS TRIGGER AS $$
DECLARE
    v_cat_year INT;
BEGIN
    IF NEW.category_id IS NOT NULL THEN
        SELECT year_id INTO v_cat_year FROM categories WHERE id = NEW.category_id;
        IF v_cat_year IS DISTINCT FROM NEW.year_id THEN
            RAISE EXCEPTION 'Category % belongs to a different year_config than event %', NEW.category_id, NEW.year_id;
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Rule #1 integrity: an event's age groups must belong to the same year_config as the event.
CREATE OR REPLACE FUNCTION fn_check_event_age_group_year() RETURNS TRIGGER AS $$
DECLARE
    v_event_year INT;
    v_ag_year    INT;
BEGIN
    SELECT year_id INTO v_event_year FROM events WHERE id = NEW.event_id;
    SELECT year_id INTO v_ag_year FROM age_groups WHERE id = NEW.age_group_id;
    IF v_event_year IS DISTINCT FROM v_ag_year THEN
        RAISE EXCEPTION 'event_age_groups: event % and age_group % belong to different year_configs', NEW.event_id, NEW.age_group_id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- A team can only be created for an event_kind='team' event.
CREATE OR REPLACE FUNCTION fn_check_team_event_kind() RETURNS TRIGGER AS $$
DECLARE
    v_kind event_kind;
BEGIN
    SELECT event_kind INTO v_kind FROM events WHERE id = NEW.event_id;
    IF v_kind IS DISTINCT FROM 'team' THEN
        RAISE EXCEPTION 'Event % is not a team event -- cannot create a team for it', NEW.event_id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Auto-fill registrations.category_id from the event if not supplied.
CREATE OR REPLACE FUNCTION fn_fill_registration_category() RETURNS TRIGGER AS $$
BEGIN
    IF NEW.category_id IS NULL THEN
        SELECT category_id INTO NEW.category_id FROM events WHERE id = NEW.event_id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Rule #1: enforce year_config.max_individual_events and category_cap per participant.
CREATE OR REPLACE FUNCTION fn_check_registration_limits() RETURNS TRIGGER AS $$
DECLARE
    v_max_events     INT;
    v_category_cap   INT;
    v_event_count    INT;
    v_category_count INT;
BEGIN
    IF NEW.participant_id IS NULL THEN
        RETURN NEW; -- team registrations are not subject to per-participant caps
    END IF;

    SELECT max_individual_events, category_cap INTO v_max_events, v_category_cap
    FROM year_config WHERE id = NEW.year_id;

    SELECT count(*) INTO v_event_count
    FROM registrations
    WHERE participant_id = NEW.participant_id
      AND year_id = NEW.year_id
      AND status <> 'withdrawn';

    IF v_event_count >= v_max_events THEN
        RAISE EXCEPTION 'Participant % already registered for the maximum % individual events', NEW.participant_id, v_max_events;
    END IF;

    IF NEW.category_id IS NOT NULL THEN
        SELECT count(*) INTO v_category_count
        FROM registrations
        WHERE participant_id = NEW.participant_id
          AND year_id = NEW.year_id
          AND category_id = NEW.category_id
          AND status <> 'withdrawn';

        IF v_category_count >= v_category_cap THEN
            RAISE EXCEPTION 'Participant % already registered for the maximum % events in this category', NEW.participant_id, v_category_cap;
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Rule #7 helper: absolute divergence threshold for an event.
CREATE OR REPLACE FUNCTION fn_divergence_abs_threshold(p_year_id INT, p_total_participants INT) RETURNS INT AS $$
DECLARE
    v_pct NUMERIC;
BEGIN
    SELECT divergence_threshold_pct INTO v_pct FROM year_config WHERE id = p_year_id;
    RETURN ROUND(p_total_participants * v_pct / 100.0);
END;
$$ LANGUAGE plpgsql STABLE;
COMMENT ON FUNCTION fn_divergence_abs_threshold(INT, INT) IS 'Rule #7: absolute divergence threshold per event = ROUND(total_participants * divergence_threshold_pct / 100).';

-- =============================================================================
-- SECTION 13: TRIGGER WIRING
-- =============================================================================

-- updated_at maintenance
CREATE TRIGGER trg_year_config_updated_at  BEFORE UPDATE ON year_config  FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
CREATE TRIGGER trg_users_updated_at        BEFORE UPDATE ON users        FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
CREATE TRIGGER trg_events_updated_at       BEFORE UPDATE ON events       FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
CREATE TRIGGER trg_judges_updated_at       BEFORE UPDATE ON judges       FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
CREATE TRIGGER trg_participants_updated_at BEFORE UPDATE ON participants FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
CREATE TRIGGER trg_registrations_updated_at BEFORE UPDATE ON registrations FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
CREATE TRIGGER trg_event_results_updated_at BEFORE UPDATE ON event_results FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
CREATE TRIGGER trg_scores_updated_at        BEFORE UPDATE ON scores        FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
CREATE TRIGGER trg_schedule_updated_at      BEFORE UPDATE ON schedule      FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- participants
CREATE TRIGGER trg_participants_01_assign_age_group
    BEFORE INSERT OR UPDATE OF dob, year_id ON participants
    FOR EACH ROW EXECUTE FUNCTION fn_assign_age_group();

CREATE TRIGGER trg_participants_02_generate_pwa_username
    BEFORE INSERT OR UPDATE OF full_name, cpr_number ON participants
    FOR EACH ROW EXECUTE FUNCTION fn_generate_pwa_username();

-- events <-> categories/age_groups year consistency
CREATE TRIGGER trg_events_check_category_year
    BEFORE INSERT OR UPDATE OF category_id, year_id ON events
    FOR EACH ROW EXECUTE FUNCTION fn_check_event_category_year();

CREATE TRIGGER trg_event_age_groups_check_year
    BEFORE INSERT OR UPDATE ON event_age_groups
    FOR EACH ROW EXECUTE FUNCTION fn_check_event_age_group_year();

-- event_criteria max-6 / sum-100
CREATE TRIGGER trg_event_criteria_check
    AFTER INSERT OR UPDATE OR DELETE ON event_criteria
    FOR EACH ROW EXECUTE FUNCTION fn_check_event_criteria();

-- event_time_slots continuous chest numbering
CREATE TRIGGER trg_time_slots_chest_calc
    AFTER INSERT OR DELETE OR UPDATE OF participant_capacity, sort_order ON event_time_slots
    FOR EACH ROW EXECUTE FUNCTION fn_recalc_slot_chest_numbers();

-- judges
CREATE TRIGGER trg_judge_assignment_blacklist_warning
    BEFORE INSERT ON judge_assignments
    FOR EACH ROW EXECUTE FUNCTION fn_warn_blacklisted_judge();

-- teams
CREATE TRIGGER trg_teams_check_event_kind
    BEFORE INSERT OR UPDATE OF event_id ON teams
    FOR EACH ROW EXECUTE FUNCTION fn_check_team_event_kind();

-- registrations: fill category first, then enforce caps (alphabetical/numeric trigger name order)
CREATE TRIGGER trg_registrations_01_fill_category
    BEFORE INSERT ON registrations
    FOR EACH ROW EXECUTE FUNCTION fn_fill_registration_category();

CREATE TRIGGER trg_registrations_02_check_limits
    BEFORE INSERT ON registrations
    FOR EACH ROW EXECUTE FUNCTION fn_check_registration_limits();

-- chest_assignments
CREATE TRIGGER trg_chest_manual_role_check
    BEFORE INSERT OR UPDATE ON chest_assignments
    FOR EACH ROW EXECUTE FUNCTION fn_enforce_manual_chest_role();

-- scores
CREATE TRIGGER trg_scores_check_max
    BEFORE INSERT OR UPDATE ON scores
    FOR EACH ROW EXECUTE FUNCTION fn_check_score_max();

-- tiebreaker_marks
CREATE TRIGGER trg_tiebreaker_marks_check_unlock
    BEFORE INSERT ON tiebreaker_marks
    FOR EACH ROW EXECUTE FUNCTION fn_check_tiebreaker_unlock();

-- event_results
CREATE TRIGGER trg_event_results_extra_prize_window
    BEFORE UPDATE ON event_results
    FOR EACH ROW WHEN (NEW.extra_prize_type IS DISTINCT FROM OLD.extra_prize_type)
    EXECUTE FUNCTION fn_check_extra_prize_window();

-- Audit triggers on sensitive tables (rule #25 ledger + rules #4,#8,#9,#10,#13,#14,#19 traceability)
CREATE TRIGGER trg_audit_chest_assignments AFTER INSERT OR UPDATE OR DELETE ON chest_assignments FOR EACH ROW EXECUTE FUNCTION fn_audit_log();
CREATE TRIGGER trg_audit_event_results      AFTER INSERT OR UPDATE OR DELETE ON event_results      FOR EACH ROW EXECUTE FUNCTION fn_audit_log();
CREATE TRIGGER trg_audit_scores             AFTER INSERT OR UPDATE OR DELETE ON scores             FOR EACH ROW EXECUTE FUNCTION fn_audit_log();
CREATE TRIGGER trg_audit_tiebreaker_marks   AFTER INSERT OR UPDATE OR DELETE ON tiebreaker_marks   FOR EACH ROW EXECUTE FUNCTION fn_audit_log();
CREATE TRIGGER trg_audit_judges             AFTER INSERT OR UPDATE OR DELETE ON judges             FOR EACH ROW EXECUTE FUNCTION fn_audit_log();
CREATE TRIGGER trg_audit_judge_flags        AFTER INSERT OR UPDATE OR DELETE ON judge_flags        FOR EACH ROW EXECUTE FUNCTION fn_audit_log();
CREATE TRIGGER trg_audit_team_members       AFTER INSERT OR UPDATE OR DELETE ON team_members       FOR EACH ROW EXECUTE FUNCTION fn_audit_log();
CREATE TRIGGER trg_audit_registrations      AFTER INSERT OR UPDATE OR DELETE ON registrations      FOR EACH ROW EXECUTE FUNCTION fn_audit_log();

-- =============================================================================
-- SECTION 14: BLUEPRINT V4 EXTENSIONS -- TIMER MODULE
-- =============================================================================
-- Adds a Timer role + per-event time limits, a timing log with auto-computed
-- overage/DQ flags, score voiding, and result disqualification/reversal.
-- Placed BEFORE the grants section so the blanket GRANT in section 15 picks
-- up the two new tables automatically.
--
-- Three deliberate deviations from the literal instruction, called out here
-- so they're not mistaken for mistakes:
--   1. users.role is an ENUM (user_role) in this schema, not a CHECK
--      constraint -- there is no users_role_check to drop. The new value is
--      added via ALTER TYPE ... ADD VALUE, and is spelled 'Timer' (PascalCase)
--      to match the existing SuperAdmin/Admin/Coordinator/Chairman/Judge/
--      Viewer convention. Use 'Timer' exactly in JWT role claims/app code.
--   2. timer_assignments.year_id now references year_config(id) -- this
--      schema's year table is year_config, not years.
--   3. participant_timings: allotted_time_s/grace_period_s are declared
--      NOT NULL (per the original draft) but are auto-backfilled from
--      events.allotted_time_seconds/grace_period_seconds by a BEFORE INSERT
--      trigger when omitted, which is what actually delivers the "immutable
--      snapshot" behaviour the original inline comment described.
-- =============================================================================

-- -----------------------------------------------------------------------
-- 14.1 New role: Timer
-- ALTER TYPE ... ADD VALUE must run outside an explicit transaction block
-- in PostgreSQL < 12; on 12+ it may run inside one but the new value cannot
-- be used by other statements in that same transaction.
-- -----------------------------------------------------------------------
ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'Timer';

-- -----------------------------------------------------------------------
-- 14.2 New columns on events: per-event timing configuration
-- -----------------------------------------------------------------------
ALTER TABLE events ADD COLUMN IF NOT EXISTS allotted_time_seconds INT NOT NULL DEFAULT 600;
ALTER TABLE events ADD COLUMN IF NOT EXISTS grace_period_seconds  INT NOT NULL DEFAULT 30;
ALTER TABLE events ADD COLUMN IF NOT EXISTS yellow_alert_seconds  INT NOT NULL DEFAULT 60;
COMMENT ON COLUMN events.allotted_time_seconds IS 'Per-participant time budget for timed events, e.g. 600 = 10 minutes.';
COMMENT ON COLUMN events.grace_period_seconds IS 'Extra time allowed past allotted_time_seconds before a DQ flag is raised.';
COMMENT ON COLUMN events.yellow_alert_seconds IS 'Warning trigger window before time runs out, e.g. 60 = 1 minute before end.';

-- -----------------------------------------------------------------------
-- 14.3 New table: participant_timings
-- -----------------------------------------------------------------------
CREATE TABLE participant_timings (
    id                    SERIAL PRIMARY KEY,
    registration_id       INT NOT NULL REFERENCES registrations(id),
    event_id              INT NOT NULL REFERENCES events(id),
    sub_group             CHAR(1),
    chest_no              INT,
    start_time            TIMESTAMPTZ,
    end_time              TIMESTAMPTZ,
    allotted_time_s       INT NOT NULL,    -- denormalised snapshot of events.allotted_time_seconds (immutability) -- see fn_fill_participant_timing_defaults()
    grace_period_s        INT NOT NULL,    -- denormalised snapshot of events.grace_period_seconds (immutability)
    time_taken_seconds    INT GENERATED ALWAYS AS
        (EXTRACT(EPOCH FROM (end_time - start_time))::INT) STORED,
    exceeded_by_seconds   INT GENERATED ALWAYS AS
        (EXTRACT(EPOCH FROM (end_time - start_time))::INT - allotted_time_s) STORED,
    within_grace          BOOL GENERATED ALWAYS AS
        (EXTRACT(EPOCH FROM (end_time - start_time))::INT > allotted_time_s
         AND EXTRACT(EPOCH FROM (end_time - start_time))::INT <= allotted_time_s + grace_period_s) STORED,
    flag_for_dq           BOOL GENERATED ALWAYS AS
        (EXTRACT(EPOCH FROM (end_time - start_time))::INT > allotted_time_s + grace_period_s) STORED,
    timed_by              INT REFERENCES users(id),
    notes                 TEXT,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (end_time IS NULL OR start_time IS NULL OR end_time >= start_time)
);
COMMENT ON TABLE participant_timings IS 'One row per timed performance. time_taken_seconds/exceeded_by_seconds/within_grace/flag_for_dq are all generated columns computed from start_time/end_time/allotted_time_s/grace_period_s -- never set them directly.';
COMMENT ON COLUMN participant_timings.flag_for_dq IS 'TRUE once overage exceeds the grace period -- surface this to event_results.is_disqualified via application workflow, it is not auto-applied.';

CREATE INDEX idx_timings_event ON participant_timings(event_id);
CREATE INDEX idx_timings_dq ON participant_timings(flag_for_dq) WHERE flag_for_dq = TRUE;

CREATE OR REPLACE FUNCTION fn_check_timing_registration_event() RETURNS TRIGGER AS $$
DECLARE
    v_reg_event_id INT;
BEGIN
    SELECT event_id INTO v_reg_event_id FROM registrations WHERE id = NEW.registration_id;
    IF v_reg_event_id IS DISTINCT FROM NEW.event_id THEN
        RAISE EXCEPTION 'participant_timings.event_id (%) does not match registrations.event_id (%) for registration %', NEW.event_id, v_reg_event_id, NEW.registration_id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_fill_participant_timing_defaults() RETURNS TRIGGER AS $$
BEGIN
    IF NEW.allotted_time_s IS NULL OR NEW.grace_period_s IS NULL THEN
        SELECT
            COALESCE(NEW.allotted_time_s, e.allotted_time_seconds),
            COALESCE(NEW.grace_period_s, e.grace_period_seconds)
        INTO NEW.allotted_time_s, NEW.grace_period_s
        FROM events e WHERE e.id = NEW.event_id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_participant_timings_01_check_event
    BEFORE INSERT OR UPDATE OF registration_id, event_id ON participant_timings
    FOR EACH ROW EXECUTE FUNCTION fn_check_timing_registration_event();

CREATE TRIGGER trg_participant_timings_02_fill_defaults
    BEFORE INSERT ON participant_timings
    FOR EACH ROW EXECUTE FUNCTION fn_fill_participant_timing_defaults();

CREATE TRIGGER trg_audit_participant_timings
    AFTER INSERT OR UPDATE OR DELETE ON participant_timings
    FOR EACH ROW EXECUTE FUNCTION fn_audit_log();

-- -----------------------------------------------------------------------
-- 14.4 New columns on scores: voiding
-- -----------------------------------------------------------------------
ALTER TABLE scores ADD COLUMN IF NOT EXISTS is_void       BOOL NOT NULL DEFAULT FALSE;
ALTER TABLE scores ADD COLUMN IF NOT EXISTS voided_reason TEXT;
ALTER TABLE scores ADD COLUMN IF NOT EXISTS voided_by     INT REFERENCES users(id);
ALTER TABLE scores ADD COLUMN IF NOT EXISTS voided_at     TIMESTAMPTZ;
ALTER TABLE scores ADD CONSTRAINT scores_void_reason_required CHECK (NOT is_void OR voided_reason IS NOT NULL);
COMMENT ON COLUMN scores.is_void IS 'When TRUE, this judge''s score for this participant/criterion is excluded from all ranking and grade calculations -- application layer must filter on is_void = FALSE wherever scores are aggregated.';

-- -----------------------------------------------------------------------
-- 14.5 New columns on event_results: disqualification + reversal
-- -----------------------------------------------------------------------
ALTER TABLE event_results ADD COLUMN IF NOT EXISTS is_disqualified         BOOL NOT NULL DEFAULT FALSE;
ALTER TABLE event_results ADD COLUMN IF NOT EXISTS disqualification_reason TEXT;
ALTER TABLE event_results ADD COLUMN IF NOT EXISTS disqualified_by         INT REFERENCES users(id);
ALTER TABLE event_results ADD COLUMN IF NOT EXISTS disqualified_at         TIMESTAMPTZ;
ALTER TABLE event_results ADD COLUMN IF NOT EXISTS dq_reversed             BOOL NOT NULL DEFAULT FALSE;
ALTER TABLE event_results ADD COLUMN IF NOT EXISTS dq_reversal_reason      TEXT;
ALTER TABLE event_results ADD COLUMN IF NOT EXISTS dq_reversed_by          INT REFERENCES users(id);
ALTER TABLE event_results ADD COLUMN IF NOT EXISTS dq_reversed_at          TIMESTAMPTZ;
ALTER TABLE event_results ADD CONSTRAINT event_results_dq_reason_required
    CHECK (NOT is_disqualified OR disqualification_reason IS NOT NULL);
ALTER TABLE event_results ADD CONSTRAINT event_results_dq_reversal_reason_required
    CHECK (NOT dq_reversed OR dq_reversal_reason IS NOT NULL);
COMMENT ON COLUMN event_results.is_disqualified IS 'Set when a timing breach (participant_timings.flag_for_dq) or other infraction disqualifies the participant from prizing.';
COMMENT ON COLUMN event_results.dq_reversed IS 'TRUE if a disqualification was later overturned on appeal. is_disqualified is left as the original record; application logic treats dq_reversed = TRUE as reinstating prize eligibility.';

-- -----------------------------------------------------------------------
-- 14.6 New table: timer_assignments
-- -----------------------------------------------------------------------
CREATE TABLE timer_assignments (
    id          SERIAL PRIMARY KEY,
    user_id     INT NOT NULL REFERENCES users(id),         -- must hold the 'Timer' role -- see trg_timer_assignments_check_role
    event_id    INT NOT NULL REFERENCES events(id),
    year_id     INT NOT NULL REFERENCES year_config(id),   -- corrected: this schema's year table is year_config, not years
    otp_sent_at TIMESTAMPTZ,                                -- manual OTP send, same pattern as judges.otp_sent_at (rule #12)
    assigned_by INT REFERENCES users(id),
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, event_id)
);
COMMENT ON TABLE timer_assignments IS 'Assigns a Timer-role user to an event for the timing module. otp_sent_at follows the same manual-at-briefing pattern as judges.otp_sent_at (rule #12), not an automatic send.';

CREATE OR REPLACE FUNCTION fn_check_timer_role() RETURNS TRIGGER AS $$
DECLARE
    v_role user_role;
BEGIN
    SELECT role INTO v_role FROM users WHERE id = NEW.user_id;
    IF v_role IS DISTINCT FROM 'Timer' THEN
        RAISE EXCEPTION 'User % does not hold the Timer role (has %) -- cannot create a timer_assignment', NEW.user_id, v_role;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_check_timer_assignment_year() RETURNS TRIGGER AS $$
DECLARE
    v_event_year INT;
BEGIN
    SELECT year_id INTO v_event_year FROM events WHERE id = NEW.event_id;
    IF v_event_year IS DISTINCT FROM NEW.year_id THEN
        RAISE EXCEPTION 'timer_assignments.year_id (%) does not match events.year_id (%) for event %', NEW.year_id, v_event_year, NEW.event_id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_timer_assignments_check_role
    BEFORE INSERT OR UPDATE OF user_id ON timer_assignments
    FOR EACH ROW EXECUTE FUNCTION fn_check_timer_role();

CREATE TRIGGER trg_timer_assignments_check_year
    BEFORE INSERT OR UPDATE OF event_id, year_id ON timer_assignments
    FOR EACH ROW EXECUTE FUNCTION fn_check_timer_assignment_year();

CREATE TRIGGER trg_audit_timer_assignments
    AFTER INSERT OR UPDATE OR DELETE ON timer_assignments
    FOR EACH ROW EXECUTE FUNCTION fn_audit_log();

-- =============================================================================
-- SECTION 15: APPLICATION DATABASE ROLE & GRANTS
-- =============================================================================
-- The Express backend should connect as kca_app (NOT as the schema owner) so the
-- audit_log INSERT-ONLY guarantee (rule #25) is real, not just a PUBLIC-role no-op.

DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'kca_app') THEN
        CREATE ROLE kca_app LOGIN PASSWORD 'CHANGE_ME_VIA_SECRETS_MANAGER';
    END IF;
END $$;

GRANT USAGE ON SCHEMA public TO kca_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO kca_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO kca_app;

-- Rule #25: audit_log is INSERT-ONLY.
REVOKE UPDATE, DELETE ON audit_log FROM kca_app;
REVOKE UPDATE, DELETE ON audit_log FROM PUBLIC;

-- =============================================================================
-- END OF SCHEMA
-- =============================================================================
